Fix for Scispark 177: Write intermediate data to HDFS while running GTG
SciSpark/SciSpark pull request #178
Opened 2016-09-22 16:48 UTC by sujen1412

2016-09-22 19:29 UTC, kwhitehall commented on src/test/python/MCSVerification.py
> +        cpTextFilesStr = 'cp {}/MCCNodesLines.json ' + workingDir + '/scisparkGTG/textFiles'.format(resultDir)
* cp line is breaking. As you are going the format option, consider something like 
cpTextFilesStr = 'cp {}/MCCEdges.txt {}/scisparkGTG/textFiles'.format(resultDir, workingDir)
* the file name MCCNodesLines.json has been changed to MCCNodes.json. Please update through out the code.

2016-09-22 19:44 UTC, kwhitehall commented on src/main/scala/org/dia/algorithms/mcc/GTGRunner.scala
> +    val outputDir = MCSUtils.testHDFSWrite(this.outputDir)
In terms of naming convention, please rename this function. In the codebase functions beginning with 'test' are found in the test dir.

2016-09-22 19:46 UTC, kwhitehall commented on src/main/scala/org/dia/algorithms/mcc/MCCOps.scala
> -      bucketSize: Int): (Int, (Iterable[MCCEdge], mutable.MutableList[mutable.HashSet[String]])) = {
update the docString please

2016-09-22 19:47 UTC, kwhitehall commented on src/main/scala/org/dia/algorithms/mcc/MCCOps.scala
Add doc string.

2016-09-22 19:50 UTC, kwhitehall requested changes

2016-09-22 20:10 UTC, sujen1412 commented on src/test/python/MCSVerification.py
> +        cpTextFilesStr = 'cp {}/MCCNodesLines.json ' + workingDir + '/scisparkGTG/textFiles'.format(resultDir)
Yes I have corrected that through out.

2016-09-22 20:10 UTC, sujen1412 commented on src/main/scala/org/dia/algorithms/mcc/GTGRunner.scala
> +    val outputDir = MCSUtils.testHDFSWrite(this.outputDir)
Ack'ed

2016-09-26 15:21 UTC, kwhitehall approved these changes

2016-09-26 15:23 UTC, kwhitehall commented
LGTM. Thanks for addressing the issues @sujen1412!

2016-09-26 15:23 UTC, merged

2016-09-26 15:58 UTC, kwhitehall commented
@sujen1412 the Python verification part of this PR is broken. As the PR #179 will have merge conflicts here, these will be resolved during that merge. In the future, please be certain to ensure that changes to variable names, files, e.g. propagate through all of the code.